language: generic
sudo: required
script: swift build
matrix:
  include:
    - os: osx
      osx_image: xcode11.4
    - os: linux
      script: swift test
      services:
        - redis-server
      dist: bionic
      install:
        - wget https://swift.org/builds/swift-5.2.3-release/ubuntu1804/swift-5.2.3-RELEASE/swift-5.2.3-RELEASE-ubuntu18.04.tar.gz
        - tar xzf swift-5.2.3-RELEASE-ubuntu18.04.tar.gz
        - export PATH=`pwd`/swift-5.2.3-RELEASE-ubuntu18.04/usr/bin:"${PATH}"
